name: Ethan Brown Photography
favicon: null
layout_spectrum: 0.4127990889828652
typography_spectrum: 0.21986116794869304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4091681856662035
  lightness: 0.7229128428734839
  saturation: 0.6729194838553667
  rhythmicContrast: 0.33345560007728636
purpose: []
